### PR TITLE
Keep up Firefox compatibility

### PR DESCRIPTION
**Pull request by timschumi**
The only API extension not supported by Firefox that is used by this plugin is the `declarativeContent` permission, and the attached function calls.

I reworked the Tab URL matching to use the traditional onTabChange-Listener method to restore compatibility, which makes the plugin work with Firefox as well.

### CODE REVIEW

**Comment by timschumi** [comment]
In case this is merged, would it be possible to publish the addon on the Firefox addons page?

There is still a warning when loading the addon, about non-persistent background scripts not being supported. In case this is an issue for uploading, it should be fine to just set that to `true`.

**Comment by lukaskollmer** [comment]
Does firefox support chrome extensions as-is, or would publishing the extension w/ mozilla require additional changes?

I'd love to support Firefox, but having to maintain two versions of the extension probably wouldn't be a good idea

**Comment by timschumi** [comment]
I only tried with the equivalent of a locally-unpacked extension so far, I haven't tried to package it yet due to lack of signing (which is usually handled by the Mozilla Addon Server). I could try and see what the process looks like though, if I'm allowed to upload it to the server myself (am I?).

Firefox generally supports a lot of the extension APIs, in some rare cases not everything has been implemented yet (as seen here or with the non-persistent background scripts not being available yet).
We'll have to see whether the warning about the background page will be an issue.

EDIT: Now I get what you meant with "as-is". iirc, Firefox uses a different packaging and signing method that is different from Chrome.

EDIT2: [The documentation](https://extensionworkshop.com/documentation/publish/package-your-extension/) implies that all the necessary files are just added to a ZIP and uploaded to the Mozilla Servers for validation and signing.

**Comment by timschumi** [comment]
I just submitted a test copy of the addon to Mozilla for signing and self-distribution as a test.

After the issue concerning the picture size in the manifest was resolved, the addon was egligible for automatic signing (addons with warnings seem to require a manual check on their side).

The only remaining issue to make this works seems to be that Mozilla doesn't allow leading zeros in any part of the addon version number (we'd have to change from `2019.06.30` to `2019.6.30` or something else entirely).

**Comment by lukaskollmer** [comment]
I'll have a look at this this soon, there's currently an update to the chrome extension pending (which has been going back and forth w/ google for 2 weeks now, because they keep rejecting it), which also requires some changes to the icon sizes, and maybe to the versioning scheme.

(also, exams)

**Comment by lukaskollmer** [comment]
update: the chrome devstore finally approved the update, i had a look at your code and it seems to work fine in both chrome and firefox, so i'll def merge it.

i think i'd prefer to publish the FF extension myself, mainly bc that would make it easier for me to keep them both up to date.

**Comment by lukaskollmer** [comment]
@timschumi done! the firefox version is available here: https://addons.mozilla.org/en-US/firefox/addon/tum-lecture-download/

**Pull request merged**
